### ISSUE TITLE
Able to run the container but no data going through

### ISSUE THREAD

**Issue by idanbenyair** [nerdalert/nflow-generator#3]
Hello,

Thanks for this great tool! For some reason I start the container and no data is going through to the destination host.

I run:
docker run -it --rm networkstatic/nflow-generator -t 96.115.208.197 -p 9990

Then on destination host I do a tcpdump:
tcpdump -i eth0 udp port 9990 -vv -X

But nothing is showing.

I'd appreciate some guidance. Thanks in advance.

**Comment by nerdalert** [comment]
Hi Idan!

I added a quick collection example to the Readme. Give it a spin and see if it works for you. https://github.com/nerdalert/nflow-generator/blob/master/README.md#run-a-test-collection

Cheers!

**Comment by idanbenyair** [comment]
Issue is resolved!
